# Generated by Django 4.1.7 on 2023-03-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_blog_created_at_remove_blog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='Blog/images'),
        ),
    ]
