# Generated by Django 4.1.7 on 2023-03-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
