# Generated by Django 4.1.7 on 2023-03-07 06:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0010_alter_comment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogpost',
        ),
    ]
